create user C##PolRouteDS identified by SYSTEM;
alter session set current_schema = C##PolRouteDS; 
GRANT ALL PRIVILEGES TO C##PolRouteDS;

CREATE TABLE district (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(255) UNIQUE NOT NULL,
    geom CLOB NOT NULL
);

CREATE TABLE neighborhood (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(4000) UNIQUE NOT NULL,
    geom CLOB NOT NULL
);

CREATE TABLE vertice (
    id NUMBER PRIMARY KEY,
    label NUMBER NOT NULL,
    district_id NUMBER NOT NULL,
    neighborhood_id NUMBER NOT NULL,
    zone_id NUMBER NOT NULL
);

CREATE TABLE segment (
    id NUMBER(19) PRIMARY KEY,
    geom SDO_GEOMETRY,
    oneway NUMBER(1),
    length NUMBER(10, 2),
    final_vertice_id NUMBER(19),
    start_vertice_id NUMBER(19)
);

CREATE TABLE data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period VARCHAR2(20),
    day NUMBER,
    month NUMBER,
    year NUMBER,
    weekday VARCHAR2(10)
);

CREATE TABLE crime (
    id NUMBER PRIMARY KEY,
    total_feminicide NUMBER,
    total_homicide NUMBER,
    total_felony_murder NUMBER,
    total_bodily_harm NUMBER,
    total_theft_cellphone NUMBER,
    total_armed_robbery_cellphone NUMBER,
    total_theft_auto NUMBER,
    total_armed_robbery_auto NUMBER,
    segment_id NUMBER,
    time_id NUMBER
);

SELECT ID, NAME, GEOM
FROM "C##POLROUTEDS".DISTRICT;

